### PR TITLE
bump to 0.1.1, update hooks and filters for WCA 0.11.0

### PR DESCRIPTION
**Pull request by rrennick**
This PR updates the WooCommerce Admin dependent code to work with WCA 0.11.0.

### CODE REVIEW

**Comment by rrennick** [comment]
@psealock If you had a couple free minutes could you pull this down, build it, and check that it loads the scheduled actions screen in the dashboard?

**Comment by rrennick** [comment]
@psealock thanks so much. 

> It looks like the start script has been removed, but adding "start": "webpack --watch" to package.json builds just fine.

I put this one back

> run npm run build:core for the production build, which gives me an error

I had been testing all the commands and generated my .pot file before testing this one. I updated the command to regenerate the .pot.

> but I'm getting a 500 on /wp-json/asa/v1/actions.

This one looks like a PHP error in the REST controller. Were there any messages in your debug.log? What version of WC did you have active?

**Comment by psealock** [comment]
On `npm run build:core`, I'm still getting this error:

```
Error: ENOENT: no such file or directory, open 'languages/action-scheduler-admin.pot'
```

I'm running master branch of WC. I get this error message on page load:

```
[28-Apr-2019 20:41:51 UTC] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /srv/www/tangaroa/public_html/wp-content/plugins/action-scheduler-admin/classes/ActionScheduler_Admin_Actions_Rest_Controller.php:131
Stack trace:
#0 /srv/www/tangaroa/public_html/wp-content/plugins/action-scheduler-admin/classes/ActionScheduler_Admin_Actions_Rest_Controller.php(131): DateTimeZone->__construct('')
#1 /srv/www/tangaroa/public_html/wp-includes/rest-api/class-wp-rest-server.php(946): ActionScheduler_Admin_Actions_Rest_Controller->get_actions(Object(WP_REST_Request))
#2 /srv/www/tangaroa/public_html/wp-includes/rest-api/class-wp-rest-server.php(329): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /srv/www/tangaroa/public_html/wp-includes/rest-api.php(309): WP_REST_Server->serve_request('/asa/v1/actions')
#4 /srv/www/tangaroa/public_html/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
#5 /srv/www/tangaroa/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /srv/ww in /srv/www/tangaroa/public_html/wp-content/plugins/action-scheduler-admin/classes/ActionScheduler_Admin_Actions_Rest_Controller.php on line 131
```

**Comment by rrennick** [comment]
@psealock Thanks, see if those two changes fix things up.

**Comment by psealock** [comment]
Still throwing errors from the `catch` statement.

```
Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone (1024)
```

In `wc-admin`, we've been doing this, which also works here.

```php
$timezone = new DateTimeZone( wc_timezone_string() ); // Pacific/Auckland
```

https://github.com/woocommerce/woocommerce-admin/blob/fc2e2678b7a0defd11506150c752d633554ea81b/includes/data-stores/class-wc-admin-reports-data-store.php#L133

The JS is building correctly though.

**Comment by rrennick** [comment]
> In wc-admin, we've been doing this, which also works here.

Thanks. I'm surprised that PHP constant is throwing an error. I'll make that change tomorrow and merge this in.

**Comment by rrennick** [comment]
```
$timezone = new DateTimeZone( wc_timezone_string() ); // Pacific/Auckland
```

Action Scheduler runs internally on UTC so the simpler fix was to only set the timezone if the timezone string was valid.

**Pull request merged**
